BabelFlow and feature extraction integration
Alpine-DAV/ascent pull request #439
Opened 2020-01-08 17:50 UTC by spetruzza

Additions:
- runtime support (BabelFlow, with default configuration using MPI)
- flow filter to perform topological segmentation using the parallel merge tree algorithm (depends and use BabelFlow as execution runtime)
- unit test for new filter

Uberenv/spack:
- new compiler config for OSX catalina
- new dependencies packages scripts (babelflow and pmt)
- not yet working as a spack variant (need some guidance)

2020-01-08 17:58 UTC, mclarsen commented
@spetruzza I haven't fully looked this over, but one thing I initially noticed is that DIY is included. This can conflict with down stream versions. Sensei uses DIY and they use ascent, so this can cause a conflict. Additionally, vtkh and vtkm both have DIY as well. In those libs, we have namespaced diy so they don't bump into each other, so I would suggest doing the same.

2020-01-08 18:07 UTC, spetruzza commented
Thanks Matt for noticing that, there was still a reference (in a CMake file) to the DIY libraries that we purposely removed as a dependency for this integration. I removed that reference.

2020-01-10 05:42 UTC, cyrush commented
`[exe: spack/bin/spack install uberenv-ascent%gcc+mpi+mfem ^python@3.6.3+babelflow ^mpich]`

In the azure yaml: I think you simply need to add the if babelflow case after the mfem case, and before the python case, that way you end up with:

`[exe: spack/bin/spack install uberenv-ascent%gcc+mpi+mfem+babelflow  ^python@3.6.3^mpich]
`

2020-01-13 22:31 UTC, mclarsen requested changes
There are some minor tweaks to the ascent package. Once this merges, we will move this package back into the spack fork. There are some other small cmake chages that we can fix later, but we can merge this soon

2020-01-13 22:31 UTC, mclarsen commented on scripts/uberenv/packages/ascent/package.py
> +    depends_on('babelflow@develop', when='+babelflow')
```
when='+babelflow+mpi'
```
We don't want to depend on MPI or have spack conflicts ~mpi+mpi

2020-01-13 22:31 UTC, mclarsen commented on scripts/uberenv/packages/ascent/package.py
> +    git      = "https://github.com/xuanhuang1/ascent.git"
This should be reverted before merging, since this is going to be merged.

2020-01-13 22:31 UTC, mclarsen commented on scripts/uberenv/packages/ascent/package.py
> +    version('babelflow',
This should be like whatever is in the main ascent package.

2020-01-13 22:39 UTC, cyrush commented
pending matt's suggested ascent package changes  -- this looks good to merge!

There are a few small improvements that can be applied to simplify how the linking and flags are specified -- but I can tackle those after this PR is merged.

2020-01-14 15:24 UTC, mclarsen approved these changes

2020-01-14 15:24 UTC, merged